// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/langfuse/terraform-provider-langfuse/internal/langfuse (interfaces: OrganizationClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	langfuse "github.com/langfuse/terraform-provider-langfuse/internal/langfuse"
)

// MockOrganizationClient is a mock of OrganizationClient interface.
type MockOrganizationClient struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationClientMockRecorder
}

// MockOrganizationClientMockRecorder is the mock recorder for MockOrganizationClient.
type MockOrganizationClientMockRecorder struct {
	mock *MockOrganizationClient
}

// NewMockOrganizationClient creates a new mock instance.
func NewMockOrganizationClient(ctrl *gomock.Controller) *MockOrganizationClient {
	mock := &MockOrganizationClient{ctrl: ctrl}
	mock.recorder = &MockOrganizationClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationClient) EXPECT() *MockOrganizationClientMockRecorder {
	return m.recorder
}

// CreateOrUpdateProjectMembership mocks base method.
func (m *MockOrganizationClient) CreateOrUpdateProjectMembership(arg0 context.Context, arg1 string, arg2 *langfuse.CreateProjectMembershipRequest) (*langfuse.ProjectMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateProjectMembership", arg0, arg1, arg2)
	ret0, _ := ret[0].(*langfuse.ProjectMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrUpdateProjectMembership indicates an expected call of CreateOrUpdateProjectMembership.
func (mr *MockOrganizationClientMockRecorder) CreateOrUpdateProjectMembership(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateProjectMembership", reflect.TypeOf((*MockOrganizationClient)(nil).CreateOrUpdateProjectMembership), arg0, arg1, arg2)
}

// CreateProject mocks base method.
func (m *MockOrganizationClient) CreateProject(arg0 context.Context, arg1 *langfuse.CreateProjectRequest) (*langfuse.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProject", arg0, arg1)
	ret0, _ := ret[0].(*langfuse.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProject indicates an expected call of CreateProject.
func (mr *MockOrganizationClientMockRecorder) CreateProject(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProject", reflect.TypeOf((*MockOrganizationClient)(nil).CreateProject), arg0, arg1)
}

// CreateProjectApiKey mocks base method.
func (m *MockOrganizationClient) CreateProjectApiKey(arg0 context.Context, arg1 string, arg2 *langfuse.CreateProjectApiKeyRequest) (*langfuse.ProjectApiKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProjectApiKey", arg0, arg1, arg2)
	ret0, _ := ret[0].(*langfuse.ProjectApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProjectApiKey indicates an expected call of CreateProjectApiKey.
func (mr *MockOrganizationClientMockRecorder) CreateProjectApiKey(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProjectApiKey", reflect.TypeOf((*MockOrganizationClient)(nil).CreateProjectApiKey), arg0, arg1, arg2)
}

// CreateSCIMUser mocks base method.
func (m *MockOrganizationClient) CreateSCIMUser(arg0 context.Context, arg1 *langfuse.SCIMUserRequest) (*langfuse.SCIMUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSCIMUser", arg0, arg1)
	ret0, _ := ret[0].(*langfuse.SCIMUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSCIMUser indicates an expected call of CreateSCIMUser.
func (mr *MockOrganizationClientMockRecorder) CreateSCIMUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSCIMUser", reflect.TypeOf((*MockOrganizationClient)(nil).CreateSCIMUser), arg0, arg1)
}

// DeleteProject mocks base method.
func (m *MockOrganizationClient) DeleteProject(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProject", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProject indicates an expected call of DeleteProject.
func (mr *MockOrganizationClientMockRecorder) DeleteProject(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProject", reflect.TypeOf((*MockOrganizationClient)(nil).DeleteProject), arg0, arg1)
}

// DeleteProjectApiKey mocks base method.
func (m *MockOrganizationClient) DeleteProjectApiKey(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProjectApiKey", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProjectApiKey indicates an expected call of DeleteProjectApiKey.
func (mr *MockOrganizationClientMockRecorder) DeleteProjectApiKey(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProjectApiKey", reflect.TypeOf((*MockOrganizationClient)(nil).DeleteProjectApiKey), arg0, arg1, arg2)
}

// DeleteProjectMembership mocks base method.
func (m *MockOrganizationClient) DeleteProjectMembership(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProjectMembership", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProjectMembership indicates an expected call of DeleteProjectMembership.
func (mr *MockOrganizationClientMockRecorder) DeleteProjectMembership(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProjectMembership", reflect.TypeOf((*MockOrganizationClient)(nil).DeleteProjectMembership), arg0, arg1, arg2)
}

// GetMembership mocks base method.
func (m *MockOrganizationClient) GetMembership(arg0 context.Context, arg1 string) (*langfuse.OrganizationMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembership", arg0, arg1)
	ret0, _ := ret[0].(*langfuse.OrganizationMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembership indicates an expected call of GetMembership.
func (mr *MockOrganizationClientMockRecorder) GetMembership(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembership", reflect.TypeOf((*MockOrganizationClient)(nil).GetMembership), arg0, arg1)
}

// GetProject mocks base method.
func (m *MockOrganizationClient) GetProject(arg0 context.Context, arg1 string) (*langfuse.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProject", arg0, arg1)
	ret0, _ := ret[0].(*langfuse.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProject indicates an expected call of GetProject.
func (mr *MockOrganizationClientMockRecorder) GetProject(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProject", reflect.TypeOf((*MockOrganizationClient)(nil).GetProject), arg0, arg1)
}

// GetProjectApiKey mocks base method.
func (m *MockOrganizationClient) GetProjectApiKey(arg0 context.Context, arg1, arg2 string) (*langfuse.ProjectApiKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectApiKey", arg0, arg1, arg2)
	ret0, _ := ret[0].(*langfuse.ProjectApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectApiKey indicates an expected call of GetProjectApiKey.
func (mr *MockOrganizationClientMockRecorder) GetProjectApiKey(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectApiKey", reflect.TypeOf((*MockOrganizationClient)(nil).GetProjectApiKey), arg0, arg1, arg2)
}

// GetProjectMembership mocks base method.
func (m *MockOrganizationClient) GetProjectMembership(arg0 context.Context, arg1, arg2 string) (*langfuse.ProjectMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectMembership", arg0, arg1, arg2)
	ret0, _ := ret[0].(*langfuse.ProjectMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectMembership indicates an expected call of GetProjectMembership.
func (mr *MockOrganizationClientMockRecorder) GetProjectMembership(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectMembership", reflect.TypeOf((*MockOrganizationClient)(nil).GetProjectMembership), arg0, arg1, arg2)
}

// ListMemberships mocks base method.
func (m *MockOrganizationClient) ListMemberships(arg0 context.Context) ([]langfuse.OrganizationMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMemberships", arg0)
	ret0, _ := ret[0].([]langfuse.OrganizationMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMemberships indicates an expected call of ListMemberships.
func (mr *MockOrganizationClientMockRecorder) ListMemberships(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMemberships", reflect.TypeOf((*MockOrganizationClient)(nil).ListMemberships), arg0)
}

// ListProjectMemberships mocks base method.
func (m *MockOrganizationClient) ListProjectMemberships(arg0 context.Context, arg1 string) ([]langfuse.ProjectMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectMemberships", arg0, arg1)
	ret0, _ := ret[0].([]langfuse.ProjectMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectMemberships indicates an expected call of ListProjectMemberships.
func (mr *MockOrganizationClientMockRecorder) ListProjectMemberships(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectMemberships", reflect.TypeOf((*MockOrganizationClient)(nil).ListProjectMemberships), arg0, arg1)
}

// ListProjects mocks base method.
func (m *MockOrganizationClient) ListProjects(arg0 context.Context) ([]*langfuse.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjects", arg0)
	ret0, _ := ret[0].([]*langfuse.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjects indicates an expected call of ListProjects.
func (mr *MockOrganizationClientMockRecorder) ListProjects(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjects", reflect.TypeOf((*MockOrganizationClient)(nil).ListProjects), arg0)
}

// RemoveMember mocks base method.
func (m *MockOrganizationClient) RemoveMember(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockOrganizationClientMockRecorder) RemoveMember(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockOrganizationClient)(nil).RemoveMember), arg0, arg1)
}

// UpdateMembership mocks base method.
func (m *MockOrganizationClient) UpdateMembership(arg0 context.Context, arg1 string, arg2 *langfuse.UpdateMembershipRequest) (*langfuse.OrganizationMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMembership", arg0, arg1, arg2)
	ret0, _ := ret[0].(*langfuse.OrganizationMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMembership indicates an expected call of UpdateMembership.
func (mr *MockOrganizationClientMockRecorder) UpdateMembership(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMembership", reflect.TypeOf((*MockOrganizationClient)(nil).UpdateMembership), arg0, arg1, arg2)
}

// UpdateProject mocks base method.
func (m *MockOrganizationClient) UpdateProject(arg0 context.Context, arg1 string, arg2 *langfuse.UpdateProjectRequest) (*langfuse.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProject", arg0, arg1, arg2)
	ret0, _ := ret[0].(*langfuse.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProject indicates an expected call of UpdateProject.
func (mr *MockOrganizationClientMockRecorder) UpdateProject(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProject", reflect.TypeOf((*MockOrganizationClient)(nil).UpdateProject), arg0, arg1, arg2)
}
