// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/langfuse/terraform-provider-langfuse/internal/langfuse (interfaces: LlmConnectionsClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	langfuse "github.com/langfuse/terraform-provider-langfuse/internal/langfuse"
)

// MockLlmConnectionsClient is a mock of LlmConnectionsClient interface.
type MockLlmConnectionsClient struct {
	ctrl     *gomock.Controller
	recorder *MockLlmConnectionsClientMockRecorder
}

// MockLlmConnectionsClientMockRecorder is the mock recorder for MockLlmConnectionsClient.
type MockLlmConnectionsClientMockRecorder struct {
	mock *MockLlmConnectionsClient
}

// NewMockLlmConnectionsClient creates a new mock instance.
func NewMockLlmConnectionsClient(ctrl *gomock.Controller) *MockLlmConnectionsClient {
	mock := &MockLlmConnectionsClient{ctrl: ctrl}
	mock.recorder = &MockLlmConnectionsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLlmConnectionsClient) EXPECT() *MockLlmConnectionsClientMockRecorder {
	return m.recorder
}

// DeleteLlmConnection mocks base method.
func (m *MockLlmConnectionsClient) DeleteLlmConnection(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLlmConnection", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLlmConnection indicates an expected call of DeleteLlmConnection.
func (mr *MockLlmConnectionsClientMockRecorder) DeleteLlmConnection(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLlmConnection", reflect.TypeOf((*MockLlmConnectionsClient)(nil).DeleteLlmConnection), arg0, arg1)
}

// ListLlmConnections mocks base method.
func (m *MockLlmConnectionsClient) ListLlmConnections(arg0 context.Context, arg1, arg2 *int) (*langfuse.ListLlmConnectionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLlmConnections", arg0, arg1, arg2)
	ret0, _ := ret[0].(*langfuse.ListLlmConnectionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLlmConnections indicates an expected call of ListLlmConnections.
func (mr *MockLlmConnectionsClientMockRecorder) ListLlmConnections(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLlmConnections", reflect.TypeOf((*MockLlmConnectionsClient)(nil).ListLlmConnections), arg0, arg1, arg2)
}

// UpsertLlmConnection mocks base method.
func (m *MockLlmConnectionsClient) UpsertLlmConnection(arg0 context.Context, arg1 *langfuse.UpsertLlmConnectionRequest) (*langfuse.LlmConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertLlmConnection", arg0, arg1)
	ret0, _ := ret[0].(*langfuse.LlmConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertLlmConnection indicates an expected call of UpsertLlmConnection.
func (mr *MockLlmConnectionsClientMockRecorder) UpsertLlmConnection(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertLlmConnection", reflect.TypeOf((*MockLlmConnectionsClient)(nil).UpsertLlmConnection), arg0, arg1)
}
